# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('time_left_terminal', models.TimeField()),
                ('time_arrived_to_client', models.TimeField()),
                ('time_left_client', models.TimeField()),
                ('time_back_to_terminal', models.TimeField()),
                ('time_unloading', models.PositiveIntegerField()),
                ('speedometer_at_leaving', models.PositiveIntegerField()),
                ('speedometer_at_arrival', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Travel Report',
                'verbose_name_plural': 'Travel Report',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=254)),
                ('takes_fuel_while_standing', models.PositiveIntegerField()),
                ('takes_fuel_while_moving', models.PositiveIntegerField()),
                ('takes_fuel_while_unloading', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicle',
            },
        ),
        migrations.AddField(
            model_name='travelreport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation_management.Vehicle'),
        ),
    ]
